In [ ]:
!pip install -q datasets pandas pyarrow

In [ ]:
import pandas as pd
import numpy as np

from datasets import load_dataset

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

In [ ]:
from datasets import load_dataset

# Load ONLY one Electronics metadata shard for testing
test_meta = load_dataset(
    "parquet",
    data_files=(
        "https://huggingface.co/datasets/"
        "McAuley-Lab/Amazon-Reviews-2023/resolve/main/"
        "raw_meta_Electronics/full-00000-of-00010.parquet"
    ),
    split="train"
)

print(test_meta)

raw_meta_Electronics/full-00000-of-00010(…): reconstructing file:   0%|          |  0.00B /  220MB

raw_meta_Electronics/full-00000-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author'],
    num_rows: 161002
})

In [ ]:
# Convert a small sample to pandas
meta_sample = test_meta.select(range(min(20, len(test_meta)))).to_pandas()

print(meta_sample.shape)
print(meta_sample.columns.tolist())

meta_sample.head()

(20, 16)
['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a new level of value in the FPV world with Fat Shark renowned performance and quality. The fun of FPV is experienced firsthand through the large screen ...,None,"{'hi_res': [None], 'large': ['https://m.media-amazon.com/images/I/41qrX56lsYL._AC_.jpg'], 'thumb': ['https://m.media-amazon.com/images/I/41qrX56lsYL._AC_US40_.jpg'], 'variant': ['MAIN']}","{'title': [], 'url': [], 'user_id': []}",Fat Shark,"[Electronics, Television & Video, Video Glasses]","{""Date First Available"": ""August 2, 2014"", ""Manufacturer"": ""Fatshark""}",B00MCW7G9M,None,None,None
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],None,"{'hi_res': ['https://m.media-amazon.com/images/I/51qxU4Zd5TL._AC_SL1050_.jpg', 'https://m.media-amazon.com/images/I/51HDwazbqNL._AC_SL1050_.jpg', 'https://m.media-amazon.com/images/I/61LRQBRVGVL._...","{'title': [], 'url': [], 'user_id': []}",SIIG,"[Electronics, Television & Video, Accessories, Cables, HDMI Cables]","{""Product Dimensions"": ""0.83 x 4.17 x 2.05 inches"", ""Item Weight"": ""5.3 ounces"", ""Item model number"": ""CE-H22B12-S1"", ""Is Discontinued By Manufacturer"": ""No"", ""Date First Available"": ""June 3, 2015...",B00YT6XQSE,None,None,None
2,Computers,"Digi-Tatoo Decal Skin Compatible With MacBook Pro 13 inch (Model A2338/ A2289/ A2251) - Protective and Decorative Full Body Laptop Skin Decal Sticker, Anti-Scratch Vinly Skin Sticker Wrap [Fresh M...",4.5,246,"[WARNING: Please IDENTIFY MODEL NUMBER on the bottom of your Macbook. Only fits for model A2338/ A2289/ A2251 (Macbook Pro 13"" w/ Touch Bar, 2022/2020 release)., Extra Care Yet Not Bulky. Our skin...",[],19.99,"{'hi_res': ['https://m.media-amazon.com/images/I/61RPxmi+mPL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61Av7GiLnWL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61vS2a5Bh4L._...","{'title': ['AL 2Sides Video', 'MacBook Protective Skin', 'ARTSO 15.6"" Laptop Skin Sticker Universal Art Cover Decal ', 'Matching display and simple installation', 'Macbook Full Body Protective Ski...",Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop Accessories, Skins & Decals, Decals]","{""Brand"": ""Digi-Tatoo"", ""Color"": ""Fresh Marble"", ""Room Type"": ""Bedroom"", ""Material"": ""Vinyl"", ""Theme"": ""Marble"", ""Style"": ""fresh marble"", ""Age Range (Description)"": ""Adult"", ""Reusability"": ""Single...",B07SM135LS,None,None,None
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22mm Quick Release Silicone Bands/Garmin Darth Vader/First Avenger/Polar Vantage Smartwatch Sport Breathable Strap Replacement for Gear S3 Classic Watchband,4.5,233,[☛NotoCity 22mm band is designed for Vivoactive 4 / Samsung Gear S3 Classic / S3 Frontier / Gear Live / Samsung Galaxy Watch 46mm / Huawei Watch GT / Tickwatch Pro / S2 / E2 / Pebble Classic / Tim...,[],9.99,"{'hi_res': ['https://m.media-amazon.com/images/I/51ajKKbi76L._AC_UL1000_.jpg', 'https://m.media-amazon.com/images/I/618Cw+LDsAL._AC_UL1000_.jpg', 'https://m.media-amazon.com/images/I/61JKP4j1hXL._...","{'title': [], 'url': [], 'user_id': []}",NotoCity,"[Electronics, Wearable Technology, Clips, Arm & Wristbands]","{""Date First Available"": ""May 29, 2020"", ""Manufacturer"": ""NotoCity""}",B089CNGZCW,None,None,None
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive Package Incredible Value Worth $145!!!, Includes all Genuine High Quality Motorola Made Accessories]","[all Genuine High Quality Motorola Made Accessories, including Multimedia Station with HDMI technology, HDMI Cable and AC Wall Charger, Motorola Navigation / Music Vehicle Charging Mount Car Dock ...",14.99,"{'hi_res': [None, None, None, None, None], 'large': ['https://m.media-amazon.com/images/I/51-DXSMlHaL._AC_.jpg', 'https://m.media-amazon.com/images/I/31HYf51qCQL._AC_.jpg', 'https://m.media-amazon...","{'title': [], 'url': [], 'user_id': []}",Verizon,"[Electronics, Computers & Accessories, Computer Accessories & Peripherals, Memory Cards, Micro SD Cards]","{""Product Dimensions"": ""11.6 x 6.9 x 3.1 inches"", ""Item Weight"": ""1.5 pounds"", ""Other display features"": ""Wireless"", ""Manufacturer"": ""Verizon"", ""Date First Available"": ""November 26, 2010""}",B004E2Z88O,None,None,None

In [ ]:
tv_keywords = [
    " smart tv",
    " television",
    " qled tv",
    " oled tv",
    " led tv",
    " uhd tv",
    " 4k tv"
]

def looks_like_tv(title):
    if title is None:
        return False

    title = title.lower()

    return any(keyword in title for keyword in tv_keywords)


tv_candidates = test_meta.filter(
    lambda row: looks_like_tv(row["title"])
)

print("TV candidates found:", len(tv_candidates))

Filter:   0%|          | 0/161002 [00:00<?, ? examples/s]

TV candidates found: 1371

In [ ]:
tv_candidates.select(
    range(min(20, len(tv_candidates)))
).to_pandas()[[
    "title",
    "parent_asin",
    "store",
    "price",
    "average_rating",
    "rating_number",
    "categories"
]]

,title,parent_asin,store,price,average_rating,rating_number,categories
0,"4K HDMI Cable 30 Foot - CAIVOV Ultra High Speed 24Gbps HDMI 2.0 Cable - 24AWG Nylon Braided HDMI Cord - 4K 60hz, HDR, 3D, 2160P, 1080P, Compatible UHD TV, Blu-ray, Xbox, PS4/3, PC, Fire TV - 30 feet",B07R4WS1P7,CAIVOV,None,4.2,5,"[Electronics, Television & Video, Accessories, Cables, HDMI Cables]"
1,Sony XBR65X900F 65-Inch 4K Ultra HD Smart LED TV with $40 Off TV Wall Mount,B07FHXH3S7,Sony,None,4.5,1724,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
2,Seiki SE32HYT 32-Inch 720p LED TV (2015 Model),B00USEZ7W4,SEIKI,None,3.9,101,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
3,MyGica ATV520 Dual-Core TV Box with Android 4.1 OS NetFlix XBMC Apps - Turn HDTV to Smart TV,B00DQDU75Q,MyGica,None,2.8,7,"[Electronics, Television & Video, Streaming Media Players]"
4,Remote Control Compatible for Samsung and LG Smart TV BN59-01185F BN59-01185F BN59-01185D BN59-01184D BN59-01182D,B08B4PCVG3,AMGUR,None,1.0,1,"[Electronics, Television & Video, Accessories, Remote Controls]"
5,LG Electronics 60UJ7700 60-Inch 4K Ultra HD Smart LED TV (2017 Model),B01MZFKIOY,LG,None,4.0,368,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
6,"SAMSUNG QN65Q60TA 65"" Q60T QLED 4K UHD HDR Smart TV Bundle with Deco Gear Home Theater Soundbar with Subwoofer and Complete Wall Mount Setup and Accessory Kit",B085HJYKZ1,SAMSUNG,None,4.3,50,"[Electronics, Television & Video, Televisions, QLED TVs]"
7,"UpBright AC DC Adapter Compatible with Milanix MX7 MX7U 7"" MX8 8"" MX12 12.1"" MX13 13.3"" MX14 14.1"" Portable Rechargeable ATSC Widescreen Digital LED Television TV Power Supply Cord Battery Charger...",B0B526LLPJ,UPBRIGHT,19.99,5.0,1,"[Electronics, Power Accessories, AC Adapters]"
8,"ISSUNTEX 10X16 ft Background Muslin Backdrop, Photo Studio, Collapsible High Density Screen for Video Photography and Television-White",B07L8YT6PG,ISSUNTEX,39.99,4.5,8746,"[Electronics, Camera & Photo, Lighting & Studio, Photo Studio, Backgrounds]"
9,Sony CRU40SG12/N Colored Speaker Grille for Sony KDL-40XBR6 Televisions (Gold),B001IWND3K,Sony,None,3.0,1,"[Electronics, Home Audio, Home Audio Accessories, Speaker Parts & Components, Speaker Grills]"
10,"Mini USB WiFi Repeater, 300M Wireless Signal Amplifier, AP WiFi Smart TV Network Adapter WiFi Hotspot Extender for TV Laptop Phone",B0B3F8CHYV,Zunate,16.59,3.6,8,"[Electronics, Computers & Accessories, Networking Products, Repeaters]"
11,"MILANIX 12 Inch LED Widescreen HDTV Television with HDMI, VGA, Built in Digital Tuner, AC/DC Compatible",B00WRO8ZSQ,MILANIX,None,3.7,239,"[Electronics, Portable Audio & Video, Portable & Handheld TVs]"
12,"Black Tilting/Tilt Wall Mount Bracket for Vizio VW42L HDTV10A 42"" LCD HDTV Television/TV",B004EVJNXG,Brateck,None,5.0,4,"[Electronics, Television & Video, Accessories, TV Mounts, Stands & Turntables, TV Wall & Ceiling Mounts]"
13,"Silicone Protective Case for Hisense EN2A27 Remote Control, Anti-Slip Battery Back Cover for Hisense EN-2A27 Smart TV Remote Skin Sleeve Protector (Glow Blue)",B09J2DS33Q,Winceed,7.99,4.5,105,"[Electronics, Television & Video, Accessories, Remote Controls]"
14,"Amazon Fire TV 65"" Omni Series 4K UHD smart TV with Dolby Vision, hands-free with Alexa",B0971XBV8M,Amazon,599.99,4.5,22744,[]
15,"Cover for Vizio Remote, Compatible with Vizio Remote Case XRT136 / XRT140 D Series Universal Smart TV Control Replacement Silicone Skin Sleeve Glow in The Dark",B0BMTVYH9G,Silicloak,5.99,4.2,118,"[Electronics, Television & Video, Accessories, Remote Controls]"
16,LG Electronics OLED55B7A 55-Inch 4K Ultra HD Smart OLED TV (2017 Model),B073K3LPGF,LG,None,3.6,435,"[Electronics, Television & Video, Televisions, OLED TVs]"
17,"XRT260 New IR Remote Control Compatible with Vizio V-Series and M-Series 4K Smart TVs with Peacock, Netflix, Prime Video, Crackle, TUBI, Watch Free+ Keys [ NO Voice Function ](with Batteries)",B0B8Z1MLVV,MEIWELL,10.99,5.0,9,"[Electronics, Television & Video, Accessories, Remote Controls]"
18,"Remote Case for Apple Tv 4th 5th Generation, Akwox Apple TV Siri Remote Cover Case with Lanyard (Purple) -not for New Apple 4k TV Series 6th Gen 2021",B07DBYS7DG,AKWOX,5.99,4.8,5430,"[Electronics, Television & Video, Accessories, Remote Controls]"
19,"Samsung Q70 Series 55-Inch Smart TV, Flat QLED 4K UHD HDR - 2019 Model",B07NW6L285,SAMSUNG,None,4.5,1832,"[Electronics, Television & Video, Televisions, QLED TVs]"

In [ ]:
def is_television(categories):
    if categories is None:
        return False

    return "Televisions" in categories


real_tvs = test_meta.filter(
    lambda row: is_television(row["categories"])
)

print("Actual televisions found:", len(real_tvs))

Filter:   0%|          | 0/161002 [00:00<?, ? examples/s]

Actual televisions found: 769

In [ ]:
real_tvs.select(
    range(min(20, len(real_tvs)))
).to_pandas()[[
    "title",
    "parent_asin",
    "store",
    "price",
    "average_rating",
    "rating_number",
    "categories"
]]

,title,parent_asin,store,price,average_rating,rating_number,categories
0,Sony KV-27HS420 27-Inch FD Trinitron WEGA HD-Ready CRT TV,B0002S9G0K,Sony,None,4.5,7,"[Electronics, Television & Video, Televisions]"
1,Sony XBR65X900F 65-Inch 4K Ultra HD Smart LED TV with $40 Off TV Wall Mount,B07FHXH3S7,Sony,None,4.5,1724,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
2,Sylvania LC427SSX 42-Inch 1080p LCD HDTV,B001S0JZRU,SYLVANIA,None,3.0,12,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
3,"Insignia - 32"" Class (31-1/2"" Diag.) - LED - 720p - 60Hz - HDTV",B0036FOREG,INSIGNIA,278.0,3.3,33,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
4,Seiki SE32HYT 32-Inch 720p LED TV (2015 Model),B00USEZ7W4,SEIKI,None,3.9,101,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
5,LG Electronics 60UJ7700 60-Inch 4K Ultra HD Smart LED TV (2017 Model),B01MZFKIOY,LG,None,4.0,368,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
6,"SAMSUNG QN65Q60TA 65"" Q60T QLED 4K UHD HDR Smart TV Bundle with Deco Gear Home Theater Soundbar with Subwoofer and Complete Wall Mount Setup and Accessory Kit",B085HJYKZ1,SAMSUNG,None,4.3,50,"[Electronics, Television & Video, Televisions, QLED TVs]"
7,"SANSUI ES50V1UA, 50 inch 4K UHD Smart LED Android TV with HDMI, USB(2022 Model)",B09R1VT1MW,SANSUI,None,4.2,2678,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
8,LG 52LG50 52-Inch 1080p LCD HDTV,B0016P2U4M,LG,None,5.0,7,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
9,4000 series LED-LCD TV,B00JP91D4O,PHILIPS,None,3.2,12,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
10,LG Electronics OLED55B7A 55-Inch 4K Ultra HD Smart OLED TV (2017 Model),B073K3LPGF,LG,None,3.6,435,"[Electronics, Television & Video, Televisions, OLED TVs]"
11,"Sony KV32HS510 32"" Flat-Screen HDTV",B00009NR16,Sony,None,3.0,10,"[Electronics, Television & Video, Televisions]"
12,"Samsung Q70 Series 55-Inch Smart TV, Flat QLED 4K UHD HDR - 2019 Model",B07NW6L285,SAMSUNG,None,4.5,1832,"[Electronics, Television & Video, Televisions, QLED TVs]"
13,Samsung PN50A450 50-Inch 720p Plasma HDTV,B0015AV3XM,SAMSUNG,None,3.3,138,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
14,Samsung QN85Q60AA 85 Inch QLED 4K UHD Smart TV (2021) (Renewed),B0979NFLH1,Amazon Renewed,1697.97,4.4,50,"[Electronics, Television & Video, Televisions, QLED TVs]"
15,Sony KV-36HS420 36-Inch FD Trinitron WEGA Hi-Scan 1080i HD-Ready TV,B0002FO3JW,Sony,None,3.0,6,"[Electronics, Television & Video, Televisions]"
16,SAMSUNG UN75RU7100FXZA Flat 75-Inch 4K UHD 7 Series Ultra HD Smart TV with HDR and Alexa Compatibility (2019 Model),B07NW6L27K,SAMSUNG,None,4.6,16148,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
17,Sony KDL60W630B 60-Inch 1080p 120Hz Smart LED TV (2014 Model),B00HPMCN8S,Sony,None,3.8,209,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
18,Toshiba REGZA 37RV530U 37-Inch 1080p LCD HDTV,B00140S2GY,Toshiba,None,3.3,14,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
19,LG 43UK6090PUA: 43 Inch Class 4K HDR Smart LED UHD TV | LG USA (Renewed),B07PRQ72WN,Amazon Renewed,None,4.0,22,"[Electronics, Television & Video, Televisions, OLED TVs]"

In [ ]:
tv_df = real_tvs.to_pandas()

tv_df["store"].value_counts().head(20)

store
SAMSUNG           144
LG                 95
Sony               72
Amazon Renewed     62
VIZIO              40
Toshiba            34
Sharp              34
Panasonic          28
PHILIPS            24
TCL                23
Hisense            15
Mitsubishi         14
Westinghouse       10
INSIGNIA            9
RCA                 9
Sceptre             9
SANSUI              8
SEIKI               7
JVC                 7
SANYO               6
Name: count, dtype: int64

In [ ]:
target_stores = {
    "SAMSUNG": "Samsung",
    "LG": "LG",
    "Sony": "Sony",
    "TCL": "TCL",
    "Hisense": "Hisense"
}

target_tv_df = tv_df[
    tv_df["store"].isin(target_stores.keys())
].copy()

target_tv_df["brand"] = target_tv_df["store"].map(target_stores)

print("Number of target-brand TVs:", len(target_tv_df))
print()
print(target_tv_df["brand"].value_counts())

Number of target-brand TVs: 349

brand
Samsung    144
LG          95
Sony        72
TCL         23
Hisense     15
Name: count, dtype: int64

In [ ]:
target_tv_df[
    [
        "brand",
        "title",
        "parent_asin",
        "price",
        "average_rating",
        "rating_number",
        "categories"
    ]
].head(30)

,brand,title,parent_asin,price,average_rating,rating_number,categories
0,Sony,Sony KV-27HS420 27-Inch FD Trinitron WEGA HD-Ready CRT TV,B0002S9G0K,None,4.5,7,"[Electronics, Television & Video, Televisions]"
1,Sony,Sony XBR65X900F 65-Inch 4K Ultra HD Smart LED TV with $40 Off TV Wall Mount,B07FHXH3S7,None,4.5,1724,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
5,LG,LG Electronics 60UJ7700 60-Inch 4K Ultra HD Smart LED TV (2017 Model),B01MZFKIOY,None,4.0,368,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
6,Samsung,"SAMSUNG QN65Q60TA 65"" Q60T QLED 4K UHD HDR Smart TV Bundle with Deco Gear Home Theater Soundbar with Subwoofer and Complete Wall Mount Setup and Accessory Kit",B085HJYKZ1,None,4.3,50,"[Electronics, Television & Video, Televisions, QLED TVs]"
8,LG,LG 52LG50 52-Inch 1080p LCD HDTV,B0016P2U4M,None,5.0,7,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
10,LG,LG Electronics OLED55B7A 55-Inch 4K Ultra HD Smart OLED TV (2017 Model),B073K3LPGF,None,3.6,435,"[Electronics, Television & Video, Televisions, OLED TVs]"
11,Sony,"Sony KV32HS510 32"" Flat-Screen HDTV",B00009NR16,None,3.0,10,"[Electronics, Television & Video, Televisions]"
12,Samsung,"Samsung Q70 Series 55-Inch Smart TV, Flat QLED 4K UHD HDR - 2019 Model",B07NW6L285,None,4.5,1832,"[Electronics, Television & Video, Televisions, QLED TVs]"
13,Samsung,Samsung PN50A450 50-Inch 720p Plasma HDTV,B0015AV3XM,None,3.3,138,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
15,Sony,Sony KV-36HS420 36-Inch FD Trinitron WEGA Hi-Scan 1080i HD-Ready TV,B0002FO3JW,None,3.0,6,"[Electronics, Television & Video, Televisions]"
16,Samsung,SAMSUNG UN75RU7100FXZA Flat 75-Inch 4K UHD 7 Series Ultra HD Smart TV with HDR and Alexa Compatibility (2019 Model),B07NW6L27K,None,4.6,16148,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
17,Sony,Sony KDL60W630B 60-Inch 1080p 120Hz Smart LED TV (2014 Model),B00HPMCN8S,None,3.8,209,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
20,TCL,TCL LE50FHDF3010TA 50-Inch 1080p 120Hz LED TV (2013 Model),B00E67CX4E,None,4.4,769,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
21,Samsung,"SAMSUNG QN55LS03BAFXZA 55"" The Frame 4K UltraHD Smart QLED TV with a VG-SCFA55WTB 55"" The Frame Customizable Bezel - Modern White (2022)",B09X9T1JCK,None,3.9,63,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
23,Samsung,Samsung UN32D4000 32-Inch 720p 60 Hz LED HDTV (Black) [2011 MODEL],B004NHGTYC,None,3.2,49,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
24,LG,"LG LT560H 32LT560H 32"" LED-LCD TV - HDTV - Edge LED Backlight - Surround Sound, Dolby Digital",B07YHVYBCM,None,3.9,16,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
26,LG,"LG 86UM8070 86-Inch, 4K LED UHD Smart TV (2019)",B07NHZJZ6N,None,4.6,424,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
27,Sony,Sony XBR-65A9G 65-inch TV: MASTER Series BRAVIA OLED 4K Ultra HD Smart TV with HDR and Alexa Compatibility - 2019 Model,B07PC8JC5F,2999.0,4.6,1069,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
32,LG,LG 55G2 55-Inch Cinema 3D 1080p 120Hz LED-LCD HDTV with Google TV and Six Pairs of 3D Glasses (2012 Model),B0078YGMFI,None,3.8,124,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
33,Samsung,"Samsung Curved 65"" 4K UHD 8 Series Smart LED TV (2018) - UN55NU8500FXZA",B07BFTKJQN,None,4.6,417,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
37,TCL,TCL LE32HDF3010 32-Inch 720p 60Hz LCD TV,B00CNR1F9I,None,4.3,25,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
39,Samsung,Samsung LNS2738D 27-Inch LCD HDTV,B000H3BKW2,None,3.0,2,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
40,LG,LG 37LG50 37-Inch 1080p LCD HDTV,B0016Z526U,None,3.3,31,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
41,Samsung,SAMSUNG 32-inch Class The Frame TV with Customizable Black Bezel (2020 Model),B088B84T21,625.98,4.5,1670,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
42,LG,"LG OLED GX Series 65” Alexa built-in Smart TV (3840 x 2160), Gallery Design, 120Hz Refresh Rate, AI-Powered 4K, Dolby Cinema, WiSA Ready, Voice Control (OLED65GXPUA, 2020)",B09738HF58,1999.99,4.5,387,"[Electronics, Television & Video, Televisions, OLED TVs]"
46,LG,"LG 65SM8100AUA Alexa Built-in Nano 8 Series 65"" 4K Ultra HD Smart LED NanoCell TV (2019)",B07PSKGMR8,None,4.6,1626,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
48,Sony,"Sony XBR65X950H 65"" X950H 4K Ultra HD LED TV with Deco Gear Soundbar Bundle",B0854NGS24,None,5.0,9,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
49,Sony,"Sony BRAVIA KDL32EX523 32-Inch 1080p LED HDTV with Integrated WiFi, Black",B004HYG9V4,None,3.1,100,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
52,Samsung,Samsung UN32ES6500 32-Inch 1080p 120Hz 3D Slim LED HDTV (Black) (2012 Model),B007BG3FE4,None,4.3,326,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"
53,Sony,Sony X80J 50 Inch TV: 4K Ultra HD LED Smart Google TV with Dolby Vision HDR and Alexa Compatibility KD50X80J- 2021 Model,B08Z31SKBB,None,4.6,2914,"[Electronics, Television & Video, Televisions, LED & LCD TVs]"

In [ ]:
summary = (
    target_tv_df
    .groupby("brand")
    .agg(
        products=("parent_asin", "nunique"),
        total_ratings=("rating_number", "sum"),
        avg_product_rating=("average_rating", "mean")
    )
    .sort_values("products", ascending=False)
)

summary

         products  total_ratings  avg_product_rating
brand
Samsung       144         105773            3.939583
LG             95          40190            4.054737
Sony           72          30954            3.954167
TCL            23          50998            4.200000
Hisense        15          17780            3.833333

In [ ]:
from datasets import load_dataset
import pandas as pd

target_stores = {
    "SAMSUNG": "Samsung",
    "LG": "LG",
    "Sony": "Sony",
    "TCL": "TCL",
    "Hisense": "Hisense"
}

all_tv_products = []

for i in range(10):
    print(f"Processing metadata shard {i + 1}/10...")

    url = (
        "https://huggingface.co/datasets/"
        "McAuley-Lab/Amazon-Reviews-2023/resolve/main/"
        f"raw_meta_Electronics/full-{i:05d}-of-00010.parquet"
    )

    # Load one shard at a time
    shard = load_dataset(
        "parquet",
        data_files=url,
        split="train"
    )

    # Keep only actual televisions
    shard = shard.filter(
        lambda row: (
            row["categories"] is not None
            and "Televisions" in row["categories"]
        )
    )

    # Keep only our five target brands
    shard = shard.filter(
        lambda row: row["store"] in target_stores
    )

    # Convert only the filtered rows to pandas
    shard_df = shard.to_pandas()

    # Standardize brand names
    shard_df["brand"] = shard_df["store"].map(target_stores)

    all_tv_products.append(shard_df)

    print(f"  Found {len(shard_df):,} target TVs")

Processing metadata shard 1/10...

Filter:   0%|          | 0/161002 [00:00<?, ? examples/s]

Filter:   0%|          | 0/769 [00:00<?, ? examples/s]

  Found 349 target TVs
Processing metadata shard 2/10...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

raw_meta_Electronics/full-00001-of-00010(…): reconstructing file:   0%|          |  0.00B /  214MB

raw_meta_Electronics/full-00001-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161002 [00:00<?, ? examples/s]

Filter:   0%|          | 0/825 [00:00<?, ? examples/s]

  Found 358 target TVs
Processing metadata shard 3/10...

raw_meta_Electronics/full-00002-of-00010(…): reconstructing file:   0%|          |  0.00B /  210MB

raw_meta_Electronics/full-00002-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/752 [00:00<?, ? examples/s]

  Found 310 target TVs
Processing metadata shard 4/10...

raw_meta_Electronics/full-00003-of-00010(…): reconstructing file:   0%|          |  0.00B /  207MB

raw_meta_Electronics/full-00003-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/767 [00:00<?, ? examples/s]

  Found 336 target TVs
Processing metadata shard 5/10...

raw_meta_Electronics/full-00004-of-00010(…): reconstructing file:   0%|          |  0.00B /  202MB

raw_meta_Electronics/full-00004-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/766 [00:00<?, ? examples/s]

  Found 295 target TVs
Processing metadata shard 6/10...

raw_meta_Electronics/full-00005-of-00010(…): reconstructing file:   0%|          |  0.00B /  193MB

raw_meta_Electronics/full-00005-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/728 [00:00<?, ? examples/s]

  Found 304 target TVs
Processing metadata shard 7/10...

raw_meta_Electronics/full-00006-of-00010(…): reconstructing file:   0%|          |  0.00B /  192MB

raw_meta_Electronics/full-00006-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/768 [00:00<?, ? examples/s]

  Found 310 target TVs
Processing metadata shard 8/10...

raw_meta_Electronics/full-00007-of-00010(…): reconstructing file:   0%|          |  0.00B /  183MB

raw_meta_Electronics/full-00007-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/811 [00:00<?, ? examples/s]

  Found 337 target TVs
Processing metadata shard 9/10...

raw_meta_Electronics/full-00008-of-00010(…): reconstructing file:   0%|          |  0.00B /  170MB

raw_meta_Electronics/full-00008-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/685 [00:00<?, ? examples/s]

  Found 262 target TVs
Processing metadata shard 10/10...

raw_meta_Electronics/full-00009-of-00010(…): reconstructing file:   0%|          |  0.00B /  164MB

raw_meta_Electronics/full-00009-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/487 [00:00<?, ? examples/s]

  Found 166 target TVs

In [ ]:
tv_products = pd.concat(
    all_tv_products,
    ignore_index=True
)

print("Total rows:", len(tv_products))
print("Unique parent_asin:", tv_products["parent_asin"].nunique())

tv_products["brand"].value_counts()

Total rows: 3027
Unique parent_asin: 3027

brand
Samsung    1323
LG          826
Sony        632
TCL         138
Hisense     108
Name: count, dtype: int64

In [ ]:
duplicates = tv_products["parent_asin"].duplicated().sum()

print("Duplicate parent_asin:", duplicates)

Duplicate parent_asin: 0

In [ ]:
brand_summary = (
    tv_products
    .groupby("brand")
    .agg(
        products=("parent_asin", "nunique"),
        total_ratings=("rating_number", "sum"),
        avg_product_rating=("average_rating", "mean")
    )
    .sort_values("products", ascending=False)
)

brand_summary

         products  total_ratings  avg_product_rating
brand
Samsung      1323         369435            3.877249
LG            826         112960            3.948184
Sony          632          81326            3.862658
TCL           138         200270            4.095652
Hisense       108          58864            3.912037

In [ ]:
tv_products.to_parquet(
    "tv_products.parquet",
    index=False
)

print("Saved tv_products.parquet")

Saved tv_products.parquet

In [ ]:
check = pd.read_parquet("tv_products.parquet")

print(check.shape)
print(check["brand"].value_counts())

(3027, 17)
brand
Samsung    1323
LG          826
Sony        632
TCL         138
Hisense     108
Name: count, dtype: int64

In [ ]:
tv_asins = set(tv_products["parent_asin"])

print("TV parent_asin count:", len(tv_asins))

TV parent_asin count: 3027

In [ ]:
!pip install -q -U datasets huggingface_hub pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.3/798.3 kB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 8.9 MB/s eta 0:00:00

In [ ]:
from datasets import load_dataset

In [ ]:
review_test = load_dataset(
    "parquet",
    data_files=(
        "https://huggingface.co/datasets/"
        "McAuley-Lab/Amazon-Reviews-2023/resolve/"
        "ac9d3ad3342d6f00bf6ad8caa2668a3f830e2dee/"
        "raw_review_Electronics/full-00000-of-00034.parquet"
    ),
    split="train"
)

print(review_test)

raw_review_Electronics/full-00000-of-000(…): reconstructing file:   0%|          |  0.00B /  318MB

raw_review_Electronics/full-00000-of-000(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase'],
    num_rows: 1290793
})

In [ ]:
print(review_test.column_names)
print("Rows in test shard:", len(review_test))

review_test.select(
    range(min(5, len(review_test)))
).to_pandas()

['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase']
Rows in test shard: 1290793

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3.0,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline so if you are sensitive/allergic to petroleum products like I am you will want to pass on these. Second: the phone adapter is useless as-is. Mine was...,"[{'attachment_type': 'IMAGE', 'large_image_url': 'https://m.media-amazon.com/images/I/71YN+Qk3kCL._SL1600_.jpg', 'medium_image_url': 'https://m.media-amazon.com/images/I/71YN+Qk3kCL._SL800_.jpg', ...",B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1658185117948,0,True
1,1.0,Didn’t work at all lenses loose/broken.,"These didn’t work. Idk if they were damaged in shipping or what, but the lenses were loose or something. I could see half a lens with its edge in the frame and the rest was missing. It looked like...",[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1592678549731,0,True
2,5.0,Excellent!,"I love these. They even come with a carry case and several sizes of ear bud inserts. Thank heaven! I get ear pain from most, but the smallest buds fit great. They also have a charger and all of ...",[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1523093017534,0,True
3,5.0,Great laptop backpack!,"I was searching for a sturdy backpack for school that would allow me to carry my laptop as well as schoolbooks. After reading many of the reviews of this bag, I placed my order and crossed my fing...",[],B001OC5JKY,B001OC5JKY,AGGZ357AO26RQZVRLGU4D4N52DZQ,1290278495000,18,True
4,5.0,Best Headphones in the Fifties price range!,I've bought these headphones three times because I love them so much and overuse them and find ways to break the plug to where I can't use my warranty. The sound and bass are awesome. Hands down m...,[],B013J7WUGC,B07CJYMRWM,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,1676601581238,0,True

In [ ]:
tv_review_test = review_test.filter(
    lambda row: row["parent_asin"] in tv_asins
)

print("Matched TV reviews:", len(tv_review_test))

Filter:   0%|          | 0/1290793 [00:00<?, ? examples/s]

Matched TV reviews: 6272

In [ ]:
tv_review_test.select(
    range(min(10, len(tv_review_test)))
).to_pandas()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Good TV for the price.,The tv overall is really good. Good picture and better sound quality than I expected. The user interface is quick and responsive. I did get a little frustrated with some of the initial set up ...,[],B08P4WR6XB,B0945WPX5W,AHCPZDDPHJE3G7M6ST5WGRPLXHOA,1650463455243,0,True
1,3.0,Great tv it’s just too wide to fit on the chest I was going to set it on,I returned it because it was too wide for the chest I was going to set it on….,[],B08BTZLBVT,B08W69YRFB,AFNT6ZJCYQN3WDIKUSWHJDXNND2Q,1676007193335,0,True
2,5.0,... in my sewing room and this one is just great. It is nice to be able to work ...,Needed a TV in my sewing room and this one is just great. It is nice to be able to work and watch at the same time. Wonderful picture.,[],B00KSBB7EY,B00KSBB7EY,AGCIVNDDRX3PXIUINEG4NCRGWCRA,1427130762000,1,True
3,5.0,good purchase,Lots of research -<br />Needed a 47 inch HDTV for living room - old style TV shelves built in to include TV position that was too.<br />Based on reviews - caught a quick sales price opportunity an...,[],B006ZH0L2E,B0078YGN34,AG35BKPUEUMX7LV5YLOQ5YCQ3GOA,1364582421000,1,True
4,5.0,Great Smart Features,"Great TV. This is my first smart TV, and I haven’t even used many smart features, but the features I’ve used are terrific. I haven’t found any modern TV with decent sound quality.",[],B07CL4GLQW,B0BTPBBL52,AHZ6XMOLEWA67S3TX7IWEXXGWSOA,1560782443284,0,True
5,5.0,Has a sleep timer and a beautiful picture. Good value,Just the right size for a bedroom. Has a sleep timer and a beautiful picture. Good value.,[],B00BCGRX9M,B00BCGRX9M,AHZ6XMOLEWA67S3TX7IWEXXGWSOA,1434585362000,0,True
6,5.0,What a beautiful TV. The price was fair,"What a beautiful TV. The price was fair. I original ordered a smaller model, but since it was backordered, the seller offered me this model at the same price as the less expensive model.",[],B0036WT3ZM,B0036WT3ZM,AHZ6XMOLEWA67S3TX7IWEXXGWSOA,1306350894000,0,True
7,1.0,Samsung 32 Art TV,"I am going to provide a list of pros and cons... but to summarize, I am really disappointed. The most disappointing thing... a HUGE BLACK box that you must use. They ""say"" it can be flush mounte...","[{'attachment_type': 'IMAGE', 'large_image_url': 'https://images-na.ssl-images-amazon.com/images/I/81KF1CgdOeL._SL1600_.jpg', 'medium_image_url': 'https://images-na.ssl-images-amazon.com/images/I/...",B08BW4JTCG,B08BW4JTCG,AFZUK3MTBIBEDQOPAK3OATUOUKLA,1606669919698,48,True
8,5.0,"Awesome TV. At $2K, it is an excellent value too.","We've had this TV a little more than 2 weeks. When the price dropped to $1997 on Amazon, I snapped it up. For the money, it is the best 4K TV out there. The smart controls work great, allowing you...",[],B00U9U9GII,B00U9U9GII,AEDNNPW6JQ4H6NPMF2FYMIUZOTGQ,1449342431000,1,True
9,5.0,Samsung Quality- Love it.,"Just received this product, hesitated to buy it. But I love all Samsung products, they are more ad expected, for quality, and the little make life easier things. I own a phone which I love from Sa...",[],B00KSBBGA4,B00LD3Q56G,AH3OG6QD6EDJGZRVCFKV4B66VWNQ,1511914429020,5,True

In [ ]:
review_columns = [
    "rating",
    "title",
    "text",
    "asin",
    "parent_asin",
    "user_id",
    "timestamp",
    "helpful_vote",
    "verified_purchase"
]

In [ ]:
import pyarrow.parquet as pq
import pyarrow.compute as pc
import pandas as pd

In [ ]:
import os
import requests
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.compute as pc

os.makedirs("review_checkpoints", exist_ok=True)
os.makedirs("temp_reviews", exist_ok=True)

COMMIT = "ac9d3ad3342d6f00bf6ad8caa2668a3f830e2dee"

review_columns = [
    "rating",
    "title",
    "text",
    "asin",
    "parent_asin",
    "user_id",
    "timestamp",
    "helpful_vote",
    "verified_purchase"
]

tv_asin_array = pa.array(list(tv_asins))

In [ ]:
def download_file(url, output_path):
    with requests.get(url, stream=True) as r:
        r.raise_for_status()

        with open(output_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)

In [ ]:
for i in range(34):

    output_file = f"review_checkpoints/tv_reviews_{i:02d}.parquet"
    temp_file = f"temp_reviews/review_{i:02d}.parquet"

    # Already completed → skip
    if os.path.exists(output_file):
        print(f"Shard {i + 1}/34 already completed — skipping")
        continue

    print(f"\nProcessing review shard {i + 1}/34...")

    url = (
        "https://huggingface.co/datasets/"
        "McAuley-Lab/Amazon-Reviews-2023/resolve/"
        f"{COMMIT}/"
        f"raw_review_Electronics/full-{i:05d}-of-00034.parquet"
    )

    # 1. Download shard temporarily
    print("  Downloading...")
    download_file(url, temp_file)

    # 2. Open parquet without loading entire shard into RAM
    parquet_file = pq.ParquetFile(temp_file)

    matched_batches = []
    matched_count = 0

    # 3. Process in batches
    for batch in parquet_file.iter_batches(
        batch_size=100_000,
        columns=review_columns
    ):

        table = pa.Table.from_batches([batch])

        mask = pc.is_in(
            table["parent_asin"],
            value_set=tv_asin_array
        )

        matched = table.filter(mask)

        if matched.num_rows > 0:
            matched_batches.append(matched)
            matched_count += matched.num_rows

    # 4. Combine matched TV reviews for this shard
    if matched_batches:
        shard_reviews = pa.concat_tables(matched_batches)

    else:
        # Create empty table with correct schema
        schema = parquet_file.schema_arrow

        selected_schema = pa.schema(
            [schema.field(col) for col in review_columns]
        )

        shard_reviews = pa.Table.from_batches(
            [],
            schema=selected_schema
        )

    # 5. Save checkpoint
    pq.write_table(
        shard_reviews,
        output_file
    )

    print(f"  Saved {matched_count:,} TV reviews")

    # 6. Delete huge original shard from Colab disk
    del parquet_file

    if os.path.exists(temp_file):
        os.remove(temp_file)

    print("  Temporary shard deleted")

Processing review shard 1/34...
  Downloading...
  Saved 6,272 TV reviews
  Temporary shard deleted

Processing review shard 2/34...
  Downloading...
  Saved 6,191 TV reviews
  Temporary shard deleted

Processing review shard 3/34...
  Downloading...
  Saved 6,252 TV reviews
  Temporary shard deleted

Processing review shard 4/34...
  Downloading...
  Saved 7,331 TV reviews
  Temporary shard deleted

Processing review shard 5/34...
  Downloading...
  Saved 6,207 TV reviews
  Temporary shard deleted

Processing review shard 6/34...
  Downloading...
  Saved 7,054 TV reviews
  Temporary shard deleted

Processing review shard 7/34...
  Downloading...
  Saved 6,295 TV reviews
  Temporary shard deleted

Processing review shard 8/34...
  Downloading...
  Saved 6,053 TV reviews
  Temporary shard deleted

Processing review shard 9/34...
  Downloading...
  Saved 8,665 TV reviews
  Temporary shard deleted

Processing review shard 10/34...
  Downloading...
  Saved 5,970 TV reviews
  Temporary shard deleted

Processing review shard 11/34...
  Downloading...
  Saved 6,229 TV reviews
  Temporary shard deleted

Processing review shard 12/34...
  Downloading...
  Saved 5,906 TV reviews
  Temporary shard deleted

Processing review shard 13/34...
  Downloading...
  Saved 7,568 TV reviews
  Temporary shard deleted

Processing review shard 14/34...
  Downloading...
  Saved 5,525 TV reviews
  Temporary shard deleted

Processing review shard 15/34...
  Downloading...
  Saved 6,803 TV reviews
  Temporary shard deleted

Processing review shard 16/34...
  Downloading...
  Saved 5,764 TV reviews
  Temporary shard deleted

Processing review shard 17/34...
  Downloading...
  Saved 6,939 TV reviews
  Temporary shard deleted

Processing review shard 18/34...
  Downloading...
  Saved 5,846 TV reviews
  Temporary shard deleted

Processing review shard 19/34...
  Downloading...
  Saved 5,628 TV reviews
  Temporary shard deleted

Processing review shard 20/34...
  Downloading...
  Saved 5,797 TV reviews
  Temporary shard deleted

Processing review shard 21/34...
  Downloading...
  Saved 6,342 TV reviews
  Temporary shard deleted

Processing review shard 22/34...
  Downloading...
  Saved 5,540 TV reviews
  Temporary shard deleted

Processing review shard 23/34...
  Downloading...
  Saved 5,791 TV reviews
  Temporary shard deleted

Processing review shard 24/34...
  Downloading...
  Saved 7,646 TV reviews
  Temporary shard deleted

Processing review shard 25/34...
  Downloading...
  Saved 6,970 TV reviews
  Temporary shard deleted

Processing review shard 26/34...
  Downloading...
  Saved 8,597 TV reviews
  Temporary shard deleted

Processing review shard 27/34...
  Downloading...
  Saved 6,769 TV reviews
  Temporary shard deleted

Processing review shard 28/34...
  Downloading...
  Saved 6,920 TV reviews
  Temporary shard deleted

Processing review shard 29/34...
  Downloading...
  Saved 7,049 TV reviews
  Temporary shard deleted

Processing review shard 30/34...
  Downloading...
  Saved 5,392 TV reviews
  Temporary shard deleted

Processing review shard 31/34...
  Downloading...
  Saved 5,605 TV reviews
  Temporary shard deleted

Processing review shard 32/34...
  Downloading...
  Saved 5,244 TV reviews
  Temporary shard deleted

Processing review shard 33/34...
  Downloading...
  Saved 5,981 TV reviews
  Temporary shard deleted

Processing review shard 34/34...
  Downloading...
  Saved 6,085 TV reviews
  Temporary shard deleted

In [ ]:
import glob

checkpoint_files = sorted(
    glob.glob("review_checkpoints/tv_reviews_*.parquet")
)

print("Checkpoint files:", len(checkpoint_files))

Checkpoint files: 34

In [ ]:
tv_reviews = pd.concat(
    [pd.read_parquet(f) for f in checkpoint_files],
    ignore_index=True
)

print("Total TV reviews:", len(tv_reviews))
print("Unique TV products:", tv_reviews["parent_asin"].nunique())

Total TV reviews: 218226
Unique TV products: 3027

In [ ]:
brand_map = (
    tv_products
    .set_index("parent_asin")["brand"]
    .to_dict()
)

tv_reviews["brand"] = tv_reviews["parent_asin"].map(brand_map)

tv_reviews["brand"].value_counts()

brand
Samsung    91917
TCL        48247
LG         42246
Sony       25575
Hisense    10241
Name: count, dtype: int64

In [ ]:
print("Missing brands:", tv_reviews["brand"].isna().sum())

Missing brands: 0

In [ ]:
review_summary = (
    tv_reviews
    .groupby("brand")
    .agg(
        reviews=("rating", "size"),
        avg_rating=("rating", "mean"),
        unique_products=("parent_asin", "nunique"),
        verified_purchase_rate=("verified_purchase", "mean"),
        avg_helpful_votes=("helpful_vote", "mean")
    )
    .sort_values("reviews", ascending=False)
)

review_summary

,reviews,avg_rating,unique_products,verified_purchase_rate,avg_helpful_votes
brand,,,,,
Samsung,91917,4.049936,1323,0.803236,4.630079
TCL,48247,3.898025,138,0.911331,2.524489
LG,42246,4.118354,826,0.837736,4.091228
Sony,25575,4.048094,632,0.724848,5.526256
Hisense,10241,3.610097,108,0.872962,3.425642

In [ ]:
tv_reviews.to_parquet(
    "tv_reviews.parquet",
    index=False
)

print("Saved tv_reviews.parquet")

Saved tv_reviews.parquet

In [ ]:
check_reviews = pd.read_parquet("tv_reviews.parquet")

print(check_reviews.shape)
print(check_reviews["brand"].value_counts())

(218226, 10)
brand
Samsung    91917
TCL        48247
LG         42246
Sony       25575
Hisense    10241
Name: count, dtype: int64