# Smart TV Data Collection

This notebook collects product metadata and consumer reviews for five major Smart TV brands — Samsung, LG, Sony, TCL, and Hisense — from the Amazon Reviews 2023 dataset.

The collection process identifies television products using product category metadata, standardizes brand names, and extracts consumer reviews associated with the selected products through `parent_asin`.

In [2]:
import pandas as pd
from datasets import load_dataset

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

## Product Metadata Collection

Product metadata is collected from the Electronics category of the Amazon Reviews 2023 dataset. Each metadata shard is processed separately to reduce memory usage.

Products are retained when their category metadata includes `Televisions`, and the sample is restricted to Samsung, LG, Sony, TCL, and Hisense. Brand names are standardized during collection for consistent downstream analysis.

In [ ]:
target_stores = {
    "SAMSUNG": "Samsung",
    "LG": "LG",
    "Sony": "Sony",
    "TCL": "TCL",
    "Hisense": "Hisense"
}

all_tv_products = []

for i in range(10):
    print(f"Processing metadata shard {i + 1}/10...")

    url = (
        "https://huggingface.co/datasets/"
        "McAuley-Lab/Amazon-Reviews-2023/resolve/main/"
        f"raw_meta_Electronics/full-{i:05d}-of-00010.parquet"
    )

    # Load one shard at a time
    shard = load_dataset(
        "parquet",
        data_files=url,
        split="train"
    )

    # Keep only actual televisions
    shard = shard.filter(
        lambda row: (
            row["categories"] is not None
            and "Televisions" in row["categories"]
        )
    )

    # Keep only our five target brands
    shard = shard.filter(
        lambda row: row["store"] in target_stores
    )

    # Convert only the filtered rows to pandas
    shard_df = shard.to_pandas()

    # Standardize brand names
    shard_df["brand"] = shard_df["store"].map(target_stores)

    all_tv_products.append(shard_df)

    print(f"  Found {len(shard_df):,} target TVs")

Processing metadata shard 1/10...

Filter:   0%|          | 0/161002 [00:00<?, ? examples/s]

Filter:   0%|          | 0/769 [00:00<?, ? examples/s]

  Found 349 target TVs
Processing metadata shard 2/10...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

raw_meta_Electronics/full-00001-of-00010(…): reconstructing file:   0%|          |  0.00B /  214MB

raw_meta_Electronics/full-00001-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161002 [00:00<?, ? examples/s]

Filter:   0%|          | 0/825 [00:00<?, ? examples/s]

  Found 358 target TVs
Processing metadata shard 3/10...

raw_meta_Electronics/full-00002-of-00010(…): reconstructing file:   0%|          |  0.00B /  210MB

raw_meta_Electronics/full-00002-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/752 [00:00<?, ? examples/s]

  Found 310 target TVs
Processing metadata shard 4/10...

raw_meta_Electronics/full-00003-of-00010(…): reconstructing file:   0%|          |  0.00B /  207MB

raw_meta_Electronics/full-00003-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/767 [00:00<?, ? examples/s]

  Found 336 target TVs
Processing metadata shard 5/10...

raw_meta_Electronics/full-00004-of-00010(…): reconstructing file:   0%|          |  0.00B /  202MB

raw_meta_Electronics/full-00004-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/766 [00:00<?, ? examples/s]

  Found 295 target TVs
Processing metadata shard 6/10...

raw_meta_Electronics/full-00005-of-00010(…): reconstructing file:   0%|          |  0.00B /  193MB

raw_meta_Electronics/full-00005-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/728 [00:00<?, ? examples/s]

  Found 304 target TVs
Processing metadata shard 7/10...

raw_meta_Electronics/full-00006-of-00010(…): reconstructing file:   0%|          |  0.00B /  192MB

raw_meta_Electronics/full-00006-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/768 [00:00<?, ? examples/s]

  Found 310 target TVs
Processing metadata shard 8/10...

raw_meta_Electronics/full-00007-of-00010(…): reconstructing file:   0%|          |  0.00B /  183MB

raw_meta_Electronics/full-00007-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/811 [00:00<?, ? examples/s]

  Found 337 target TVs
Processing metadata shard 9/10...

raw_meta_Electronics/full-00008-of-00010(…): reconstructing file:   0%|          |  0.00B /  170MB

raw_meta_Electronics/full-00008-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/685 [00:00<?, ? examples/s]

  Found 262 target TVs
Processing metadata shard 10/10...

raw_meta_Electronics/full-00009-of-00010(…): reconstructing file:   0%|          |  0.00B /  164MB

raw_meta_Electronics/full-00009-of-00010(…): downloading bytes:           |  0.00B

Generating train split: 0 examples [00:00, ? examples/s]

Filter:   0%|          | 0/161001 [00:00<?, ? examples/s]

Filter:   0%|          | 0/487 [00:00<?, ? examples/s]

  Found 166 target TVs

### Combine and Validate Product Metadata

The filtered metadata shards are combined into a single product-level dataset. Basic validation checks are used to confirm the number of products, unique product identifiers, and brand distribution.

In [ ]:
tv_products = pd.concat(
    all_tv_products,
    ignore_index=True
)

print("Total rows:", len(tv_products))
print("Unique parent_asin:", tv_products["parent_asin"].nunique())

tv_products["brand"].value_counts()

Total rows: 3027
Unique parent_asin: 3027

brand
Samsung    1323
LG          826
Sony        632
TCL         138
Hisense     108
Name: count, dtype: int64

In [ ]:
duplicates = tv_products["parent_asin"].duplicated().sum()

print("Duplicate parent_asin:", duplicates)

Duplicate parent_asin: 0

In [ ]:
brand_summary = (
    tv_products
    .groupby("brand")
    .agg(
        products=("parent_asin", "nunique"),
        total_ratings=("rating_number", "sum"),
        avg_product_rating=("average_rating", "mean")
    )
    .sort_values("products", ascending=False)
)

brand_summary

         products  total_ratings  avg_product_rating
brand
Samsung      1323         369435            3.877249
LG            826         112960            3.948184
Sony          632          81326            3.862658
TCL           138         200270            4.095652
Hisense       108          58864            3.912037

### Save Product Dataset

The validated product metadata is saved as a Parquet file for use in the subsequent cleaning and analysis notebooks.

In [ ]:
tv_products.to_parquet(
    "../data/tv_products.parquet",
    index=False
)

print("Saved ../data/tv_products.parquet")

Saved tv_products.parquet

In [ ]:
check = pd.read_parquet("../data/tv_products.parquet")

print(check.shape)
print(check["brand"].value_counts())

(3027, 17)
brand
Samsung    1323
LG          826
Sony        632
TCL         138
Hisense     108
Name: count, dtype: int64

In [ ]:
tv_asins = set(tv_products["parent_asin"])

print("TV parent_asin count:", len(tv_asins))

TV parent_asin count: 3027

## Consumer Review Collection

Consumer reviews are collected for the Smart TV products identified above. Reviews are matched to products using `parent_asin`.

Because the full Electronics review dataset is large, review shards are downloaded and filtered individually. Intermediate checkpoints are saved so that completed shards do not need to be processed again.

In [ ]:
import os
import requests
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.compute as pc

os.makedirs("review_checkpoints", exist_ok=True)
os.makedirs("temp_reviews", exist_ok=True)

COMMIT = "ac9d3ad3342d6f00bf6ad8caa2668a3f830e2dee"

review_columns = [
    "rating",
    "title",
    "text",
    "asin",
    "parent_asin",
    "user_id",
    "timestamp",
    "helpful_vote",
    "verified_purchase"
]

tv_asin_array = pa.array(list(tv_asins))

In [ ]:
def download_file(url, output_path):
    with requests.get(url, stream=True) as r:
        r.raise_for_status()

        with open(output_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)

In [ ]:
for i in range(34):

    output_file = f"review_checkpoints/tv_reviews_{i:02d}.parquet"
    temp_file = f"temp_reviews/review_{i:02d}.parquet"

    # Already completed → skip
    if os.path.exists(output_file):
        print(f"Shard {i + 1}/34 already completed — skipping")
        continue

    print(f"\nProcessing review shard {i + 1}/34...")

    url = (
        "https://huggingface.co/datasets/"
        "McAuley-Lab/Amazon-Reviews-2023/resolve/"
        f"{COMMIT}/"
        f"raw_review_Electronics/full-{i:05d}-of-00034.parquet"
    )

    # 1. Download shard temporarily
    print("  Downloading...")
    download_file(url, temp_file)

    # 2. Open parquet without loading entire shard into RAM
    parquet_file = pq.ParquetFile(temp_file)

    matched_batches = []
    matched_count = 0

    # 3. Process in batches
    for batch in parquet_file.iter_batches(
        batch_size=100_000,
        columns=review_columns
    ):

        table = pa.Table.from_batches([batch])

        mask = pc.is_in(
            table["parent_asin"],
            value_set=tv_asin_array
        )

        matched = table.filter(mask)

        if matched.num_rows > 0:
            matched_batches.append(matched)
            matched_count += matched.num_rows

    # 4. Combine matched TV reviews for this shard
    if matched_batches:
        shard_reviews = pa.concat_tables(matched_batches)

    else:
        # Create empty table with correct schema
        schema = parquet_file.schema_arrow

        selected_schema = pa.schema(
            [schema.field(col) for col in review_columns]
        )

        shard_reviews = pa.Table.from_batches(
            [],
            schema=selected_schema
        )

    # 5. Save checkpoint
    pq.write_table(
        shard_reviews,
        output_file
    )

    print(f"  Saved {matched_count:,} TV reviews")

    # 6. Delete huge original shard from Colab disk
    del parquet_file

    if os.path.exists(temp_file):
        os.remove(temp_file)

    print("  Temporary shard deleted")

Processing review shard 1/34...
  Downloading...
  Saved 6,272 TV reviews
  Temporary shard deleted

Processing review shard 2/34...
  Downloading...
  Saved 6,191 TV reviews
  Temporary shard deleted

Processing review shard 3/34...
  Downloading...
  Saved 6,252 TV reviews
  Temporary shard deleted

Processing review shard 4/34...
  Downloading...
  Saved 7,331 TV reviews
  Temporary shard deleted

Processing review shard 5/34...
  Downloading...
  Saved 6,207 TV reviews
  Temporary shard deleted

Processing review shard 6/34...
  Downloading...
  Saved 7,054 TV reviews
  Temporary shard deleted

Processing review shard 7/34...
  Downloading...
  Saved 6,295 TV reviews
  Temporary shard deleted

Processing review shard 8/34...
  Downloading...
  Saved 6,053 TV reviews
  Temporary shard deleted

Processing review shard 9/34...
  Downloading...
  Saved 8,665 TV reviews
  Temporary shard deleted

Processing review shard 10/34...
  Downloading...
  Saved 5,970 TV reviews
  Temporary shard deleted

Processing review shard 11/34...
  Downloading...
  Saved 6,229 TV reviews
  Temporary shard deleted

Processing review shard 12/34...
  Downloading...
  Saved 5,906 TV reviews
  Temporary shard deleted

Processing review shard 13/34...
  Downloading...
  Saved 7,568 TV reviews
  Temporary shard deleted

Processing review shard 14/34...
  Downloading...
  Saved 5,525 TV reviews
  Temporary shard deleted

Processing review shard 15/34...
  Downloading...
  Saved 6,803 TV reviews
  Temporary shard deleted

Processing review shard 16/34...
  Downloading...
  Saved 5,764 TV reviews
  Temporary shard deleted

Processing review shard 17/34...
  Downloading...
  Saved 6,939 TV reviews
  Temporary shard deleted

Processing review shard 18/34...
  Downloading...
  Saved 5,846 TV reviews
  Temporary shard deleted

Processing review shard 19/34...
  Downloading...
  Saved 5,628 TV reviews
  Temporary shard deleted

Processing review shard 20/34...
  Downloading...
  Saved 5,797 TV reviews
  Temporary shard deleted

Processing review shard 21/34...
  Downloading...
  Saved 6,342 TV reviews
  Temporary shard deleted

Processing review shard 22/34...
  Downloading...
  Saved 5,540 TV reviews
  Temporary shard deleted

Processing review shard 23/34...
  Downloading...
  Saved 5,791 TV reviews
  Temporary shard deleted

Processing review shard 24/34...
  Downloading...
  Saved 7,646 TV reviews
  Temporary shard deleted

Processing review shard 25/34...
  Downloading...
  Saved 6,970 TV reviews
  Temporary shard deleted

Processing review shard 26/34...
  Downloading...
  Saved 8,597 TV reviews
  Temporary shard deleted

Processing review shard 27/34...
  Downloading...
  Saved 6,769 TV reviews
  Temporary shard deleted

Processing review shard 28/34...
  Downloading...
  Saved 6,920 TV reviews
  Temporary shard deleted

Processing review shard 29/34...
  Downloading...
  Saved 7,049 TV reviews
  Temporary shard deleted

Processing review shard 30/34...
  Downloading...
  Saved 5,392 TV reviews
  Temporary shard deleted

Processing review shard 31/34...
  Downloading...
  Saved 5,605 TV reviews
  Temporary shard deleted

Processing review shard 32/34...
  Downloading...
  Saved 5,244 TV reviews
  Temporary shard deleted

Processing review shard 33/34...
  Downloading...
  Saved 5,981 TV reviews
  Temporary shard deleted

Processing review shard 34/34...
  Downloading...
  Saved 6,085 TV reviews
  Temporary shard deleted

### Combine and Validate Consumer Reviews

The filtered review checkpoints are combined into a single dataset. Reviews are mapped to their corresponding brands using `parent_asin`, and validation checks are performed to identify missing brand assignments and summarize review coverage.

In [ ]:
import glob

checkpoint_files = sorted(
    glob.glob("review_checkpoints/tv_reviews_*.parquet")
)

print("Checkpoint files:", len(checkpoint_files))

Checkpoint files: 34

In [ ]:
tv_reviews = pd.concat(
    [pd.read_parquet(f) for f in checkpoint_files],
    ignore_index=True
)

print("Total TV reviews:", len(tv_reviews))
print("Unique TV products:", tv_reviews["parent_asin"].nunique())

Total TV reviews: 218226
Unique TV products: 3027

In [ ]:
brand_map = (
    tv_products
    .set_index("parent_asin")["brand"]
    .to_dict()
)

tv_reviews["brand"] = tv_reviews["parent_asin"].map(brand_map)

tv_reviews["brand"].value_counts()

brand
Samsung    91917
TCL        48247
LG         42246
Sony       25575
Hisense    10241
Name: count, dtype: int64

In [ ]:
print("Missing brands:", tv_reviews["brand"].isna().sum())

Missing brands: 0

In [ ]:
review_summary = (
    tv_reviews
    .groupby("brand")
    .agg(
        reviews=("rating", "size"),
        avg_rating=("rating", "mean"),
        unique_products=("parent_asin", "nunique"),
        verified_purchase_rate=("verified_purchase", "mean"),
        avg_helpful_votes=("helpful_vote", "mean")
    )
    .sort_values("reviews", ascending=False)
)

review_summary

,reviews,avg_rating,unique_products,verified_purchase_rate,avg_helpful_votes
brand,,,,,
Samsung,91917,4.049936,1323,0.803236,4.630079
TCL,48247,3.898025,138,0.911331,2.524489
LG,42246,4.118354,826,0.837736,4.091228
Sony,25575,4.048094,632,0.724848,5.526256
Hisense,10241,3.610097,108,0.872962,3.425642

### Save Review Dataset

The collected reviews are saved as a Parquet file for subsequent cleaning and consumer experience analysis.

In [ ]:
tv_reviews.to_parquet(
    "../data/tv_reviews.parquet",
    index=False
)

print("Saved ../data/tv_reviews.parquet")

Saved tv_reviews.parquet

In [ ]:
check_reviews = pd.read_parquet("../data/tv_reviews.parquet")

print(check_reviews.shape)
print(check_reviews["brand"].value_counts())

(218226, 10)
brand
Samsung    91917
TCL        48247
LG         42246
Sony       25575
Hisense    10241
Name: count, dtype: int64